-- MySQL Script generated by MySQL Workbench
-- 10/03/17 05:44:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theatre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`theatre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `city_id` INT NULL,
  `slug` VARCHAR(45) NULL,
  `address` VARCHAR(125) NULL,
  `phone` VARCHAR(60) NULL,
  `lat` DECIMAL(10,0) NULL,
  `lng` DECIMAL(10,0) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`htm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`htm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theatre_id` INT NULL,
  `day` INT NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `synopsis` TEXT NULL,
  `mtix_code` VARCHAR(20) NULL,
  `produser` VARCHAR(60) NULL,
  `sutradara` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `production` VARCHAR(45) NULL,
  `casts` TEXT NULL,
  `category` TEXT NULL,
  `rate` INT NULL,
  `cover` VARCHAR(45) NULL,
  `trailer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theatre_id` INT NULL,
  `movie_id` INT NULL,
  `date` DATE NULL,
  `showtime` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
